spring:
  datasource:
    url: jdbc:postgresql://kandula.db.elephantsql.com:5432/uwlypkzj
    username: uwlypkzj
    password: XHNfUr4mLmG44BqFEvrhWfjGoAx9kfFI
    driver-class-name: org.postgresql.Driver